// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// subsequence
SEXP subsequence(SEXP x, int start, int end);
RcppExport SEXP _stratbuilder3gen_subsequence(SEXP xSEXP, SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(subsequence(x, start, end));
    return rcpp_result_gen;
END_RCPP
}
// lag_cpp
SEXP lag_cpp(SEXP x, int n);
RcppExport SEXP _stratbuilder3gen_lag_cpp(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(lag_cpp(x, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stratbuilder3gen_subsequence", (DL_FUNC) &_stratbuilder3gen_subsequence, 3},
    {"_stratbuilder3gen_lag_cpp", (DL_FUNC) &_stratbuilder3gen_lag_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_stratbuilder3gen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
