# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subsequence <- function(x, start, end) {
    .Call(`_stratbuilder3gen_subsequence`, x, start, end)
}

lag_cpp <- function(x, n = 1L) {
    .Call(`_stratbuilder3gen_lag_cpp`, x, n)
}

